#!/bin/sh
set -eu

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_FILE="$ROOT_DIR/Config/GeneratedCloudSecrets.xcconfig"

xcconfig_escape() {
    printf '%s' "$1" | sed 's,//,/$()/,g'
}

write_setting() {
    key="$1"
    value="${2:-}"

    if [ -n "$value" ]; then
        printf '%s = %s\n' "$key" "$(xcconfig_escape "$value")" >> "$OUTPUT_FILE"
    fi
}

{
    printf '// Generated by Xcode Cloud before xcodebuild. Do not commit.\n'
    printf '// Values come from App Store Connect shared environment variables.\n'
} > "$OUTPUT_FILE"

write_setting "STRO_SPEAK_AI_API_KEY" "${STRO_SPEAK_AI_API_KEY:-}"
write_setting "STRO_SPEAK_AI_BASE_URL" "${STRO_SPEAK_AI_BASE_URL:-}"
write_setting "STRO_SPEAK_TRANSCRIPTION_API_KEY" "${STRO_SPEAK_TRANSCRIPTION_API_KEY:-}"
write_setting "STRO_SPEAK_TRANSCRIPTION_BASE_URL" "${STRO_SPEAK_TRANSCRIPTION_BASE_URL:-}"
